#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

ENV_NAME="$(require_env_name "${1:-}")"
TFVARS_FILE="$(env_tfvars_path "$ENV_NAME")"
GENERATED_FILE="$(generated_tfvars_path "$ENV_NAME")"

require_command aws
require_command tofu
[[ -f "$TFVARS_FILE" ]] || fail "Missing env config: $TFVARS_FILE"

PROJECT_NAME="$(tfvar_value "$TFVARS_FILE" project_name)"
REGION="$(tfvar_value "$TFVARS_FILE" aws_region)"
USER_POOL_ID="$(tofu_output cognito_user_pool_id)"
APP_URL="$(tofu_output app_url)"

[[ -n "$PROJECT_NAME" ]] || PROJECT_NAME="data-chord"
[[ -n "$REGION" ]] || fail "aws_region is missing in $TFVARS_FILE"
[[ -n "$USER_POOL_ID" ]] || fail "Cognito user pool does not exist yet. Run the first OpenTofu apply."
[[ -n "$APP_URL" ]] || fail "app_url output does not exist yet. Run the first OpenTofu apply."

CLIENT_NAME="${PROJECT_NAME}-${ENV_NAME}-alb"
CALLBACK_URL="${APP_URL}/oauth2/idpresponse"

CLIENT_ID="$(
  aws cognito-idp list-user-pool-clients \
    --region "$REGION" \
    --user-pool-id "$USER_POOL_ID" \
    --max-results 60 \
    --query "UserPoolClients[?ClientName=='$CLIENT_NAME'].ClientId | [0]" \
    --output text
)"

if [[ "$CLIENT_ID" == "None" || -z "$CLIENT_ID" ]]; then
  log "Creating Cognito app client: $CLIENT_NAME"
  CLIENT_ID="$(
    aws cognito-idp create-user-pool-client \
      --region "$REGION" \
      --user-pool-id "$USER_POOL_ID" \
      --client-name "$CLIENT_NAME" \
      --generate-secret \
      --allowed-o-auth-flows-user-pool-client \
      --allowed-o-auth-flows code \
      --allowed-o-auth-scopes openid email profile \
      --supported-identity-providers COGNITO \
      --callback-urls "$CALLBACK_URL" \
      --logout-urls "$APP_URL" \
      --query "UserPoolClient.ClientId" \
      --output text
  )"
else
  log "Updating Cognito app client: $CLIENT_NAME"
  aws cognito-idp update-user-pool-client \
    --region "$REGION" \
    --user-pool-id "$USER_POOL_ID" \
    --client-id "$CLIENT_ID" \
    --client-name "$CLIENT_NAME" \
    --allowed-o-auth-flows-user-pool-client \
    --allowed-o-auth-flows code \
    --allowed-o-auth-scopes openid email profile \
    --supported-identity-providers COGNITO \
    --callback-urls "$CALLBACK_URL" \
    --logout-urls "$APP_URL" \
    >/dev/null
fi

mkdir -p "$(dirname "$GENERATED_FILE")"
printf '# Generated by infra/scripts/bootstrap-cognito-client.sh. Do not edit by hand.\ncognito_user_pool_client_id = "%s"\n' "$CLIENT_ID" >"$GENERATED_FILE"
log "Recorded Cognito app client ID in $GENERATED_FILE"
