#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

ENV_NAME="$(require_env_name "${1:-}")"
MODE="${2:-deploy}"
BACKEND_FILE="$(backend_config_path "$ENV_NAME")"
ENV_TFVARS_FILE="$(env_tfvars_path "$ENV_NAME")"
GENERATED_TFVARS_FILE="$(generated_tfvars_path "$ENV_NAME")"

export AWS_PROFILE="${AWS_PROFILE:-strides}"
AWS_REGION_VALUE="$(tfvar_value "$ENV_TFVARS_FILE" aws_region)"
[[ -n "$AWS_REGION_VALUE" ]] || fail "aws_region is missing in $ENV_TFVARS_FILE"
export AWS_REGION="$AWS_REGION_VALUE"
export AWS_DEFAULT_REGION="$AWS_REGION_VALUE"

require_command aws
require_command git
require_command tofu

[[ -f "$BACKEND_FILE" ]] || fail "Missing backend config: $BACKEND_FILE"
[[ -f "$ENV_TFVARS_FILE" ]] || fail "Missing env config: $ENV_TFVARS_FILE"

tofu_args=(
  "-var-file=$ENV_TFVARS_FILE"
  "-var-file=$GENERATED_TFVARS_FILE"
)

git_branch() {
  git -C "$REPO_DIR" branch --show-current
}

git_commit() {
  git -C "$REPO_DIR" rev-parse HEAD
}

remote_branch_matches_commit() {
  local branch="$1"
  local commit="$2"
  local remote_commit
  remote_commit="$(
    git -C "$REPO_DIR" ls-remote origin "refs/heads/$branch" |
      awk '{print $1}'
  )"
  [[ "$remote_commit" == "$commit" ]]
}

ensure_deployable_git_state() {
  local branch commit dirty_status
  branch="$(git_branch)"
  commit="$(git_commit)"
  dirty_status="$(git -C "$REPO_DIR" status --porcelain)"

  [[ -n "$branch" ]] || fail "Cannot deploy from a detached HEAD."

  if [[ -n "$dirty_status" && "${DATA_CHORD_DEPLOY_ALLOW_DIRTY:-}" != "1" ]]; then
    fail "Working tree has uncommitted changes. Commit them, or rerun with DATA_CHORD_DEPLOY_ALLOW_DIRTY=1 to deploy the current HEAD anyway."
  fi

  if ! remote_branch_matches_commit "$branch" "$commit"; then
    fail "origin/$branch does not match local HEAD. Push branch '$branch' before deploying."
  fi

  log "Deploy source: $branch @ ${commit:0:12}"
}

init_tofu() {
  log "Initializing OpenTofu backend for $ENV_NAME"
  tofu -chdir="$INFRA_DIR" init \
    -backend-config="$BACKEND_FILE" \
    -input=false \
    -reconfigure
}

apply_stack() {
  log "Applying OpenTofu stack for $ENV_NAME"
  tofu -chdir="$INFRA_DIR" apply -input=false -auto-approve "${tofu_args[@]}"
}

plan_stack() {
  log "Planning OpenTofu stack for $ENV_NAME"
  tofu -chdir="$INFRA_DIR" plan -input=false "${tofu_args[@]}"
}

has_cognito_client_id() {
  local client_id
  client_id="$(tfvar_value "$GENERATED_TFVARS_FILE" cognito_user_pool_client_id)"
  [[ -n "$client_id" ]]
}

clear_cognito_client_id() {
  printf '# Generated by infra/scripts. Do not edit by hand.\ncognito_user_pool_client_id = ""\n' >"$GENERATED_TFVARS_FILE"
}

bootstrap_state() {
  "$SCRIPT_DIR/bootstrap-state.sh" "$ENV_NAME"
}

ensure_secret() {
  "$SCRIPT_DIR/bootstrap-secrets.sh" "$ENV_NAME" ensure
}

check_secret() {
  "$SCRIPT_DIR/bootstrap-secrets.sh" "$ENV_NAME" check
}

ensure_cognito_client_if_possible() {
  if [[ -z "$(tofu_output cognito_user_pool_id)" ]]; then
    log "Cognito user pool is not created yet; will bootstrap client after first apply"
    return 1
  fi

  "$SCRIPT_DIR/bootstrap-cognito-client.sh" "$ENV_NAME"
}

start_build() {
  local project_name commit
  project_name="$(tofu_output codebuild_project_name)"
  commit="$(git_commit)"
  [[ -n "$project_name" ]] || fail "CodeBuild project is not available yet. Apply infrastructure first."

  log "Starting CodeBuild project: $project_name at ${commit:0:12}"
  aws codebuild start-build \
    --project-name "$project_name" \
    --source-version "$commit" \
    --query "build.id" \
    --output text
}

print_build_logs_hint() {
  local group_name="$1"
  local stream_name="$2"
  local deep_link="$3"

  if [[ "$group_name" != "None" && "$stream_name" != "None" ]]; then
    log "Recent CodeBuild log lines:"
    aws logs get-log-events \
      --log-group-name "$group_name" \
      --log-stream-name "$stream_name" \
      --limit 80 \
      --query "events[].message" \
      --output text || true
  fi

  [[ "$deep_link" == "None" ]] || log "CodeBuild logs: $deep_link"
}

watch_build() {
  local build_id="$1"
  local previous=""
  local status phase group_name stream_name deep_link fields

  log "Watching CodeBuild build: $build_id"
  while true; do
    fields="$(
      aws codebuild batch-get-builds \
        --ids "$build_id" \
        --query "builds[0].[buildStatus,currentPhase,logs.groupName,logs.streamName,logs.deepLink]" \
        --output text
    )"
    read -r status phase group_name stream_name deep_link <<<"$fields"

    if [[ "$status:$phase" != "$previous" ]]; then
      log "CodeBuild status: $status ($phase)"
      previous="$status:$phase"
    fi

    case "$status" in
      SUCCEEDED)
        return 0
        ;;
      FAILED | FAULT | STOPPED | TIMED_OUT)
        print_build_logs_hint "$group_name" "$stream_name" "$deep_link"
        fail "CodeBuild finished with status: $status"
        ;;
    esac

    sleep 10
  done
}

print_target_health() {
  local target_group_arn
  target_group_arn="$(tofu_output target_group_arn)"
  [[ -n "$target_group_arn" ]] || return 0

  log "Current target health:"
  aws elbv2 describe-target-health \
    --target-group-arn "$target_group_arn" \
    --query "TargetHealthDescriptions[].{Target:Target.Id,State:TargetHealth.State,Reason:TargetHealth.Reason,Description:TargetHealth.Description}" \
    --output table || true
}

watch_ecs_rollout() {
  local cluster service deadline fields state desired running pending event previous
  cluster="$(tofu_output ecs_cluster_name)"
  service="$(tofu_output ecs_service_name)"
  [[ -n "$cluster" && -n "$service" ]] || fail "ECS service outputs are not available yet."

  log "Watching ECS rollout: $cluster/$service"
  deadline=$((SECONDS + 900))
  previous=""

  while (( SECONDS < deadline )); do
    fields="$(
      aws ecs describe-services \
        --cluster "$cluster" \
        --services "$service" \
        --query "services[0].deployments[?status=='PRIMARY'] | [0].[rolloutState,desiredCount,runningCount,pendingCount]" \
        --output text
    )"
    read -r state desired running pending <<<"$fields"
    event="$(
      aws ecs describe-services \
        --cluster "$cluster" \
        --services "$service" \
        --query "services[0].events[0].message" \
        --output text
    )"

    if [[ "$state:$desired:$running:$pending:$event" != "$previous" ]]; then
      log "ECS status: state=${state:-unknown} desired=${desired:-?} running=${running:-?} pending=${pending:-?}"
      [[ "$event" == "None" ]] || log "Latest ECS event: $event"
      previous="$state:$desired:$running:$pending:$event"
    fi

    if [[ "$state" == "COMPLETED" && "$running" == "$desired" && "$pending" == "0" ]]; then
      log "ECS rollout is stable"
      return 0
    fi

    sleep 15
  done

  print_target_health
  fail "Timed out waiting for ECS rollout"
}

print_status() {
  local app_url cluster service build_project
  app_url="$(tofu_output app_url)"
  cluster="$(tofu_output ecs_cluster_name)"
  service="$(tofu_output ecs_service_name)"
  build_project="$(tofu_output codebuild_project_name)"

  [[ -z "$app_url" ]] || log "App URL: $app_url"
  [[ -z "$build_project" ]] || log "CodeBuild project: $build_project"

  if [[ -n "$cluster" && -n "$service" ]]; then
    aws ecs describe-services \
      --cluster "$cluster" \
      --services "$service" \
      --query "services[0].{Desired:desiredCount,Running:runningCount,Pending:pendingCount,Status:status,LatestEvent:events[0].message}" \
      --output table || true
  fi

  print_target_health
}

tail_logs() {
  local ecs_group codebuild_group
  ecs_group="$(tofu_output ecs_log_group)"
  codebuild_group="$(tofu_output codebuild_log_group)"

  [[ -z "$ecs_group" ]] || {
    log "Recent ECS app logs: $ecs_group"
    aws logs tail "$ecs_group" --since 30m || true
  }

  [[ -z "$codebuild_group" ]] || {
    log "Recent CodeBuild logs: $codebuild_group"
    aws logs tail "$codebuild_group" --since 30m || true
  }
}

run_full_deploy() {
  local build_id app_url

  log "Using AWS profile: $AWS_PROFILE"
  ensure_deployable_git_state
  bootstrap_state
  ensure_generated_tfvars "$ENV_NAME"
  ensure_secret
  init_tofu

  ensure_cognito_client_if_possible || clear_cognito_client_id
  apply_stack

  if ! has_cognito_client_id; then
    "$SCRIPT_DIR/bootstrap-cognito-client.sh" "$ENV_NAME"
    apply_stack
  fi

  build_id="$(start_build)"
  watch_build "$build_id"
  watch_ecs_rollout

  app_url="$(tofu_output app_url)"
  log "Deploy complete: $app_url"
}

case "$MODE" in
  deploy)
    run_full_deploy
    ;;
  plan)
    log "Using AWS profile: $AWS_PROFILE"
    bootstrap_state
    ensure_generated_tfvars "$ENV_NAME"
    check_secret
    init_tofu
    if [[ -z "$(tofu_output cognito_user_pool_id)" ]]; then
      clear_cognito_client_id
    fi
    plan_stack
    ;;
  status)
    bootstrap_state
    ensure_generated_tfvars "$ENV_NAME"
    init_tofu
    print_status
    ;;
  logs)
    bootstrap_state
    ensure_generated_tfvars "$ENV_NAME"
    init_tofu
    tail_logs
    ;;
  build)
    ensure_deployable_git_state
    bootstrap_state
    ensure_generated_tfvars "$ENV_NAME"
    init_tofu
    build_id="$(start_build)"
    watch_build "$build_id"
    watch_ecs_rollout
    ;;
  *)
    fail "Unknown deploy mode: $MODE"
    ;;
esac
