#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_DIR="$(cd "$INFRA_DIR/.." && pwd)"

log() {
  printf '[%s] %s\n' "$(date +%H:%M:%S)" "$*" >&2
}

fail() {
  printf '[%s] ERROR: %s\n' "$(date +%H:%M:%S)" "$*" >&2
  exit 1
}

require_env_name() {
  local env_name="${1:-}"
  case "$env_name" in
    staging | prod)
      printf '%s\n' "$env_name"
      ;;
    *)
      fail "Choose an environment: just deploy staging or just deploy prod."
      ;;
  esac
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Missing required command: $1"
}

env_tfvars_path() {
  printf '%s/env/%s.tfvars\n' "$INFRA_DIR" "$1"
}

backend_config_path() {
  printf '%s/env/%s.backend.hcl\n' "$INFRA_DIR" "$1"
}

generated_tfvars_path() {
  printf '%s/generated/%s.tfvars\n' "$INFRA_DIR" "$1"
}

tfvar_value() {
  local file="$1"
  local key="$2"
  awk -F= -v key="$key" '
    $1 ~ "^[[:space:]]*" key "[[:space:]]*$" {
      value = $2
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", value)
      gsub(/^"|"$/, "", value)
      print value
      exit
    }
  ' "$file"
}

backend_value() {
  tfvar_value "$1" "$2"
}

ensure_generated_tfvars() {
  local env_name="$1"
  local generated_file
  generated_file="$(generated_tfvars_path "$env_name")"
  mkdir -p "$(dirname "$generated_file")"
  if [[ ! -f "$generated_file" ]]; then
    printf '# Generated by infra/scripts. Do not edit by hand.\ncognito_user_pool_client_id = ""\n' >"$generated_file"
  fi
}

tofu_output() {
  local output_name="$1"
  tofu -chdir="$INFRA_DIR" output -raw "$output_name" 2>/dev/null || true
}
